/**
 * Drizzle migration template for Groupon Encore services.
 *
 * This file is auto-generated by: drizzle-kit generate
 * Manual migrations should follow this pattern.
 *
 * Conventions:
 *   - Files live in: encore-[service-name]/drizzle/
 *   - Format: NNNN_description.ts (e.g., 0001_create_deals_table.ts)
 *   - Applied by: drizzle-kit migrate (or via Encore's migration hook)
 *
 * Safety rules:
 *   - Never DROP COLUMN in a single deploy — first make nullable, then remove in next deploy
 *   - Never DROP TABLE without confirming no reads/writes in production first
 *   - Always add indexes CONCURRENTLY for large tables (> 1M rows)
 *   - Adding a NOT NULL column requires a default — always provide one
 */

import { sql } from 'drizzle-orm';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

export async function up(db: PostgresJsDatabase): Promise<void> {
  // ── Create table ──────────────────────────────────────────────────────────
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS [entities] (
      id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      name        VARCHAR(255) NOT NULL,
      description TEXT,
      status      VARCHAR(50)  NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'inactive', 'deleted')),
      amount      DECIMAL(10, 2),
      is_enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // ── Indexes ───────────────────────────────────────────────────────────────
  // Use CONCURRENTLY on large tables — cannot be run inside a transaction
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS [entities]_status_idx
      ON [entities] (status);
  `);

  // ── Trigger: auto-update updated_at ──────────────────────────────────────
  await db.execute(sql`
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ language 'plpgsql';
  `);

  await db.execute(sql`
    CREATE TRIGGER [entities]_updated_at
      BEFORE UPDATE ON [entities]
      FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
  `);
}

export async function down(db: PostgresJsDatabase): Promise<void> {
  await db.execute(sql`DROP TRIGGER IF EXISTS [entities]_updated_at ON [entities];`);
  await db.execute(sql`DROP INDEX IF EXISTS [entities]_status_idx;`);
  await db.execute(sql`DROP TABLE IF EXISTS [entities];`);
}

// ─────────────────────────────────────────────
// Common migration patterns — copy as needed
// ─────────────────────────────────────────────

// Add a nullable column (safe — no table lock)
// await db.execute(sql`ALTER TABLE [entities] ADD COLUMN IF NOT EXISTS new_col TEXT;`);

// Add a NOT NULL column with default (safe — provide default)
// await db.execute(sql`ALTER TABLE [entities] ADD COLUMN IF NOT EXISTS new_col TEXT NOT NULL DEFAULT '';`);

// Safe column removal (2-step):
// Step 1 (this deploy): make nullable, stop writing to it
// await db.execute(sql`ALTER TABLE [entities] ALTER COLUMN old_col DROP NOT NULL;`);
// Step 2 (next deploy): drop the column
// await db.execute(sql`ALTER TABLE [entities] DROP COLUMN IF EXISTS old_col;`);

// Add a foreign key
// await db.execute(sql`
//   ALTER TABLE [entities]
//     ADD CONSTRAINT [entities]_owner_id_fk
//     FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE;
// `);
